### ISSUE TITLE
Heads up, export workspaces broken for MarkLogic 9.

### ISSUE THREAD

**Issue by grechaw** [marklogic-community/ml-app-deployer#136] opened 2017-02-22 19:21 UTC
(Looks like this is an ml-javaclient-util issue)

I tried running mlExportWorkspaces against MarkLogic 9, and the QC library changed out from under you.  I hacked the server to get it working by adding this function.  So if you change the QCONSOLE.Scripts code to call this directly maybe that's a workaround.

I personally think QConsole could use a published API.  This functionality is too good to be subject to the foibles of internal modules.

```
(what I added to qconsole-model -- this function disappeared in 9)

 declare function qconsole-model:default-content-source(
 ) as xs:string
 {
     xdmp:database("Documents") || ":" || xdmp:database("Modules") || ":/"
 };
```

**Comment by TammyHale** [comment] 2017-02-22 21:52
Thanks! I'll look into it.

**Comment by rjrudin** [comment] 2017-06-19 12:30
@TammyHale One thing we'll need is the ability for this code to see whether ML is version 8 or 9, and then execute the appropriate code.

**Comment by rjrudin** [comment] 2018-02-17 16:33
Duplicate of https://github.com/marklogic-community/ml-javaclient-util/issues/92

**Closed by rjrudin** 2018-02-17 16:33 UTC
