### ISSUE TITLE
Support updating task server properties

### ISSUE THREAD

**Issue by derms** [marklogic-community/ml-app-deployer#188] opened 2017-09-08 09:06 UTC
Relevant REST API endpoint is

https://docs.marklogic.com/REST/PUT/manage/v2/task-servers/[id-or-name]/properties

**Comment by rjrudin** [comment] 2017-12-11 19:52
This is a dupe of #212 , which was closed in 3.2.0

**Closed by rjrudin** 2017-12-11 19:52 UTC
