### ISSUE TITLE
Error submitting role/privileges via CMA

### ISSUE THREAD

**Issue by dixitsingla** [marklogic-community/ml-app-deployer#413] opened 2020-07-15 07:34 UTC
@rjrudin  
Facing issue while deploying roles and privileges via gradle v3.17.0

This is related to issue:
https://github.com/marklogic-community/ml-app-deployer/issues/397

A work around was provided for this which is to deploy the roles first and then deploy the privileges. Also assign the roles in the privileges json config file.

When tried deploying the roles and privileges via gradle getting the same issue as same as earlier(#397 ).

`conflict has been detected:MANAGE-CONFLICTINGCONFIG: (err:FOER0000) A conflict has been detected: roles differ.false roles differ./MarkLogic/manage/models/security-model.xqy37056umod:check-same-strings((), `

I have added the roles assignment in the privileges config file and changed the deployment order to make sure roles are deployed first. (previously privileges were created first then roles,  and privileges were configured in the roles json config file)

`mlAppDeployer.getCommand('DeployRolesCommand').setExecuteSortOrder(4)`

below is final formed CMA request. In the request "role" key is missing in the "privileges" block although it is present in the privileges config json file.

first time the deployment will work on second time it will through an error as mentioned above.

```
{
    "config": [
        {
            "role": [
                {
                    "role-name": "role-1",
                    "description": "role-1",
                    "role": []
                }
            ]
        },
        {
            "privilege": [
                {
                    "privilege-name": "privileges-1",
                    "action": "/dir/",
                    "kind": "uri"
                }
            ]
        }
    ]
}
```

role json config: (ml-config/security/roles/role-1.json)

```
{
    "role-name":  "role-1",
    "description":  "role-1",
    "role":  []
}
```

privileges json config: (ml-config/security/privileges/privileges-1.json)

```
{
    "privilege-name":  "privileges-1",
    "action":  "/dir/",
    "kind":  "uri",
    "role": ["role-1"]
}
```

**Comment by rjrudin** [comment] 2020-07-15 13:35
Hi @dixitsingla - can you try reproducing the error by posting that payload to /manage/v3 via e.g. curl? Note that the bug referenced in #397  has not yet been fixed in MarkLogic, so it may be that the same bug is causing the issue here. 

One option is to disable CMA usage either entirely - mlDeployWithCma=false - or disable it for privileges - mlDeployPrivilegesWithCma=false .

**Comment by dixitsingla** [comment] 2020-07-21 06:47
The bug referenced #397 is marked as "Will not fix.", and provided a work around to create the role first and assign it to the privilege.

I am able to reproduce the issue from postman (this is the same bug as earlier).


`mlDeployPrivilegesWithCma=false` This one worked for me. (not to using the CMA while deploying the privileges)

**Comment by rjrudin** [comment] 2020-07-21 12:34
So the workaround in bug 54048 is not working for you? #393 in ml-app-deployer allows for roles to be defined in privileges while still deploying privileges first - the roles are removed from the privileges so they can be deployed, and then "DeployPrivilegeRolesCommand" runs after roles are deployed so that the roles referenced by privileges can be safely added. 

I don't think you should need to adjust the order of deploying roles.

**Comment by rjrudin** [comment] 2020-09-08 11:55
@dixitsingla Was reviewing this, and I'm not clear yet on what if anything should be changed in ml-app-deployer. If you can reproduce the issue in postman, then it's typically outside the scope of ml-app-deployer and something to be resolved in ML.

**Comment by rjrudin** [comment] 2020-10-14 15:27
@dixitsingla  Any update here on whether you get the issue via e.g. curl or postman too?

**Comment by rjrudin** [comment] 2020-12-10 18:47
Closing due to no response. Please reopen if you can respond to the above question.

**Closed by rjrudin** 2020-12-10 18:47 UTC
